version: '3.2'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  broker:
    build:
      context: ./
      target: broker
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - BROKER_PORT=8080
  
  core:
    build:
      context: ./
      target: core
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - GATEWAY_PORT=8080
    ports:
      - 8080:8080

  ui:
    build:
      context: ./
      target: ui
    ports:
      - 3000:3000
